name: Keep a Changelog

on:
  pull_request: {}

jobs:
  test:
    runs-on: ${{ env.UBUNTU_VERSION }}
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 0
    - run: bash -c "! git diff --exit-code origin/master... CHANGELOG.md"
