name: esprc

on:
  push:
    branches:
      - master
  pull_request: {}

jobs:
  parse:
    runs-on: ${{ env.UBUNTU_VERSION }}
    strategy:
      matrix:
        ap:
          - "201"
          - "203"
    steps:
    - uses: actions/checkout@v1
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ env.MSRV }}
        profile: minimal
        default: true
        override: true
    - uses: actions-rs/cargo@v1
      with:
        command: run
        args: --release --bin esprc -- ./schemas/APs/10303-${{ matrix.ap }}-aim-long.exp --check

  generate:
    runs-on: ${{ env.UBUNTU_VERSION }}
    strategy:
      matrix:
        ap:
          - "201"
          - "203"
    steps:
    - uses: actions/checkout@v1
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ env.MSRV }}
        profile: minimal
        components: rustfmt
        default: true
        override: true
    - name: Generate binding
      run: |
        set -eo pipefail
        cargo run --release --bin esprc -- ./schemas/APs/10303-${{ matrix.ap }}-aim-long.exp | rustfmt > ./ruststep/src/ap${{ matrix.ap }}.rs
        git diff --exit-code
